### ISSUE TITLE
Was an IC Clamp considered and rejected for hooking up the IC to the programmer

### ISSUE THREAD

**Issue by chandlercv** [mikedehaan/mad-phenom#1]
In the how-to, a fair amount of attention is paid to holding the wires on the chip by hand.

Was an IC clamp (like https://www.amazon.com/GGGarden-1-27mm-Programmer-Testing-Adapter) considered and rejected for making the connection to the programmer?

If so, why was it rejected?

**Comment by bjoham** [comment]
The cards I have had access to, it is possible to use the six through holes close to the battery input instead. I use male/male breadboard wires between the programmer connector and the phenom card. The connector mess at the card is enough to hold them in place by themselves.
NOTE! Make sure there are no shorts!

**Comment by bjoham** [comment]
A newer card had these on the bottom side instead. (Hidden by the plastic holders.)

**Comment by mikedehaan** [comment]
An SOIC-14 IC clamp can absolutely be used. the problem is, it's a very tight fit. For the one I bought, I had to sand off a portion of the clamp to get it to seat properly. The clamp is a great idea. Especially if you're doing more than one board.

I've heard from many sources about the holes in the board. I have not tested them, but it does look like they can be used to connect an ISP programmer.
