### ISSUE TITLE
Full "schematics" of the trigger board

### ISSUE THREAD

**Issue by bjoham** [mikedehaan/mad-phenom#2]
In an effort finding a simpler programming method, and if possible more functions, I have more or less reverse engineered the PCB design. 

Findings:
* There is an ISP connector available close to the battery input
* I might have the X7 Classic card as the power and selector position is accessible through SW
* The battery voltage is readable through pin 13, roughly with a 373/32 divisor
* The original card has the brown-out detection enabled (BODLEVEL1: 2.5-2.9V)
* The RG LEDs are driven as a pair with opposite polarity and can be activated only individually

**Comment by mikedehaan** [comment]
I'll try to address your points individually:

1. I have seen this on several boards as well, but never tried to use it. I would be interested to know if this works, but mostly I've been focused on getting them out the door and back into people's hands as quickly as possible.
2. That certainly sounds like the x7classic. The board uses an extra state in the hall effect sensor to get another set of firing options rather than the mechanical semi-auto mode on the x7phenom
3. This was one of those things I would have loved to implement, but never put the time toward figuring it out. The demand has been super low so I chose to focus more on firing modes and improving performance overall.
4. Similar to #3. Demand just wasn't there and most of the memory is now used toward other features. Might not be enough room on an existing chip to add this back in.
5. This is true. To achieve the "orange" color when saving settings on the board, I had to quickly alternate between red and green (2ms between each flash). Fun.

One more note regarding brownout and battery voltage....Independent of the software, **the PCB will consume power even when turned off**. Please remove your battery after each day of use to prevent draining your battery entirely.
